/// Embedded command content from agents/*.md files
/// This module uses include_str! to embed all command content at compile time

pub fn get_command_content(name: &str) -> Option<&'static str> {
    match name {
        "api-design" => Some(include_str!("../../agents/api-design.md")),
        "api-docs" => Some(include_str!("../../agents/api-docs.md")),
        "clean-code" => Some(include_str!("../../agents/clean-code.md")),
        "clean-deps" => Some(include_str!("../../agents/clean-deps.md")),
        "db" => Some(include_str!("../../agents/db.md")),
        "debug" => Some(include_str!("../../agents/debug.md")),
        "default" => Some(include_str!("../../agents/default.md")),
        "deploy-devops" => Some(include_str!("../../agents/deploy-devops.md")),
        "design-ui" => Some(include_str!("../../agents/design-ui.md")),
        "doc" => Some(include_str!("../../agents/doc.md")),
        "doc-api" => Some(include_str!("../../agents/doc-api.md")),
        "doc-architect" => Some(include_str!("../../agents/doc-architect.md")),
        "doc-architecture" => Some(include_str!("../../agents/doc-architecture.md")),
        "doc-business" => Some(include_str!("../../agents/doc-business.md")),
        "doc-contributing" => Some(include_str!("../../agents/doc-contributing.md")),
        "doc-install" => Some(include_str!("../../agents/doc-install.md")),
        "doc-log" => Some(include_str!("../../agents/doc-log.md")),
        "doc-migration" => Some(include_str!("../../agents/doc-migration.md")),
        "doc-prd" => Some(include_str!("../../agents/doc-prd.md")),
        "doc-readme" => Some(include_str!("../../agents/doc-readme.md")),
        "doc-risks" => Some(include_str!("../../agents/doc-risks.md")),
        "doc-roadmap" => Some(include_str!("../../agents/doc-roadmap.md")),
        "doc-security" => Some(include_str!("../../agents/doc-security.md")),
        "doc-techstack" => Some(include_str!("../../agents/doc-techstack.md")),
        "doc-todo" => Some(include_str!("../../agents/doc-todo.md")),
        "doc-writer" => Some(include_str!("../../agents/doc-writer.md")),
        "git-commit" => Some(include_str!("../../agents/git-commit.md")),
        "git-pr" => Some(include_str!("../../agents/git-pr.md")),
        "git-workflow" => Some(include_str!("../../agents/git-workflow.md")),
        "init" => Some(include_str!("../../agents/init.md")),
        "lang-js" => Some(include_str!("../../agents/lang-js.md")),
        "lang-php" => Some(include_str!("../../agents/lang-php.md")),
        "lang-ts" => Some(include_str!("../../agents/lang-ts.md")),
        "migrate-code" => Some(include_str!("../../agents/migrate-code.md")),
        "migrate-db" => Some(include_str!("../../agents/migrate-db.md")),
        "perf-optimize" => Some(include_str!("../../agents/perf-optimize.md")),
        "perf-profile" => Some(include_str!("../../agents/perf-profile.md")),
        "refactor" => Some(include_str!("../../agents/refactor.md")),
        "review" => Some(include_str!("../../agents/review.md")),
        "review-architect" => Some(include_str!("../../agents/review-architect.md")),
        "review-audit" => Some(include_str!("../../agents/review-audit.md")),
        "review-code" => Some(include_str!("../../agents/review-code.md")),
        "sec-audit" => Some(include_str!("../../agents/sec-audit.md")),
        "sec-practices" => Some(include_str!("../../agents/sec-practices.md")),
        "test" => Some(include_str!("../../agents/test.md")),
        "update" => Some(include_str!("../../agents/update.md")),
        "vibekit" => Some(include_str!("../../agents/vibekit.md")),
        _ => None,
    }
}

pub fn get_command_description(name: &str) -> &'static str {
    match name {
        "api-design" => "Design API endpoints and structure",
        "api-docs" => "Generate API documentation",
        "clean-code" => "Clean and refactor code",
        "clean-deps" => "Clean up dependencies",
        "db" => "Database design and operations",
        "debug" => "Debug issues and errors",
        "default" => "Default VibeKit command",
        "deploy-devops" => "Deployment and DevOps setup",
        "design-ui" => "UI/UX design guidance",
        "doc" => "General documentation",
        "doc-api" => "API documentation",
        "doc-architect" => "Architecture documentation",
        "doc-architecture" => "System architecture docs",
        "doc-business" => "Business documentation",
        "doc-contributing" => "Contributing guidelines",
        "doc-install" => "Installation documentation",
        "doc-log" => "Changelog documentation",
        "doc-migration" => "Migration documentation",
        "doc-prd" => "Product requirements document",
        "doc-readme" => "README documentation",
        "doc-risks" => "Risk assessment documentation",
        "doc-roadmap" => "Product roadmap documentation",
        "doc-security" => "Security documentation",
        "doc-techstack" => "Tech stack documentation",
        "doc-todo" => "TODO documentation",
        "doc-writer" => "Documentation writer assistant",
        "git-commit" => "Git commit message helper",
        "git-pr" => "Pull request helper",
        "git-workflow" => "Git workflow guidance",
        "init" => "Initialize new project",
        "lang-js" => "JavaScript best practices",
        "lang-php" => "PHP best practices",
        "lang-ts" => "TypeScript best practices",
        "migrate-code" => "Code migration helper",
        "migrate-db" => "Database migration helper",
        "perf-optimize" => "Performance optimization",
        "perf-profile" => "Performance profiling",
        "refactor" => "Code refactoring guidance",
        "review" => "Code review",
        "review-architect" => "Architecture review",
        "review-audit" => "Comprehensive code audit",
        "review-code" => "Code review guidance",
        "sec-audit" => "Security audit",
        "sec-practices" => "Security best practices",
        "test" => "Testing guidance",
        "update" => "Update dependencies and code",
        "vibekit" => "VibeKit help and information",
        _ => "Unknown command",
    }
}
